
CREATE TABLE VOLUNTEER_DETAILS
(
	VOLUNTEERID INT PRIMARY KEY,
	VOLUNTEER_NAME VARCHAR(50) NOT NULL,
	RES_ADDRESS VARCHAR(1000),
	OFF_ADDRESS VARCHAR(1000),
	RES_PHONE VARCHAR(20),
	OFF_PHONE VARCHAR(20),
	MOBILE_PHONE VARCHAR(20),
	EMAIL VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PIN INT,
	STILL_INTERESTED CHAR(1) DEFAULT 'Y',
	BEST_TIME_TO_CONTACT VARCHAR(100),
	TIME_COMMITMENT VARCHAR(100),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50) NOT NULL,
	MODIFIED_DATE DATE NOT NULL
);


INSERT INTO "PUBLIC"
	."VOLUNTEER_DETAILS"
		(
			"VOLUNTEERID"
			,"VOLUNTEER_NAME"
			,"RES_ADDRESS"
			,"OFF_ADDRESS"
			,"RES_PHONE"
			,"OFF_PHONE"
			,"MOBILE_PHONE"
			,"EMAIL"
			,"CITY"
			,"STATE"
			,"PIN"
			,"STILL_INTERESTED"
			,"BEST_TIME_TO_CONTACT"
			,"TIME_COMMITMENT"
			,"IS_ACTIVE"
			,"MODIFIED_BY"
			,"MODIFIED_DATE"
		)
	VALUES
		(
			2,'Santosh I','aaa, bbb street, ccc, Maharastra','xxx yyy street, zzz, Maharastra','123 456 2345','222 444 2323','7788372821'
			,'x@y.com','Mumbai','Maharastra',NULL,'Y',NULL,NULL,'Y','santosh',GETDATE()); 
INSERT INTO "PUBLIC"
	."VOLUNTEER_DETAILS"
		(
			"VOLUNTEERID"
			,"VOLUNTEER_NAME"
			,"RES_ADDRESS"
			,"OFF_ADDRESS"
			,"RES_PHONE"
			,"OFF_PHONE"
			,"MOBILE_PHONE"
			,"EMAIL"
			,"CITY"
			,"STATE"
			,"PIN"
			,"STILL_INTERESTED"
			,"BEST_TIME_TO_CONTACT"
			,"TIME_COMMITMENT"
			,"IS_ACTIVE"
			,"MODIFIED_BY"
			,"MODIFIED_DATE"
		)
	VALUES
		(
			1,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) 
				
				



CREATE TABLE DONOR_DETAILS
(
	DONORID INT PRIMARY KEY,
	DONOR_NAME VARCHAR(50) NOT NULL,
	RES_ADDRESS VARCHAR(1000),
	OFF_ADDRESS VARCHAR(1000),
	RES_PHONE VARCHAR(20),
	OFF_PHONE VARCHAR(20),
	MOBILE_PHONE VARCHAR(20),
	EMAIL VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PIN INT,
	REFERRAL VARCHAR(50),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50) NOT NULL,
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (REFERRAL) REFERENCES public.VOLUNTEER_DETAILS (VOLUNTEERID)
);

CREATE TABLE FORM
(
	FORMID INT PRIMARY KEY,
	FORM_NAME VARCHAR(50) NOT NULL,
	FORM_DESC VARCHAR(500),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL
);

CREATE TABLE BENEFICIARY
(
	BENEFICIARYID INT PRIMARY KEY,
	NGONAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(1000),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PIN INT,
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL
);


CREATE TABLE DONOR_PLEDGE 
(
	PLEDGEID INT PRIMARY KEY,
	DONORID INT,
	BENEFICIARYID INT,
	FORMID INT,
	DONATION_FREQUENCY VARCHAR(100) NOT NULL, 
	AMOUNT DOUBLE NOT NULL,
	DATE_FROM DATE,
	DATE_UNTIL DATE,
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (DONORID) REFERENCES public.DONOR_DETAILS (DONORID),
	FOREIGN KEY (FORMID) REFERENCES public.FORM (FORMID),
	FOREIGN KEY (BENEFICIARYID) REFERENCES public.BENEFICIARY (BENEFICIARYID)
);


CREATE TABLE DONOR_TRAN
(
	PLEDGEID INT,
	DEPOSIT_TYPE VARCHAR(25) NOT NULL,
	DEPOSIT_DETAILS VARCHAR(1000),
	DEPOSIT_DATE DATE NOT NULL,
	ENCASHED_DATE DATE NOT NULL,
	AMOUNT DOUBLE NOT NULL,
	VERIFIED char(1) DEFAULT 'N',
	RECEIPT VARCHAR(1000),
	REMARKS VARCHAR(5000),
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (PLEDGEID) REFERENCES public.DONOR_PLEDGE (PLEDGEID)
);

CREATE TABLE SKILLSET
(
	SKILLID INT PRIMARY KEY,
	SKILL_NAME VARCHAR(100) NOT NULL,
	SKILL_DETAILS VARCHAR(1000),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL
	
);

CREATE TABLE VOLUNTEER_SKILLS
(	
	VOLUNTEERID INT,
	SKILLID INT,
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (VOLUNTEERID) REFERENCES public.VOLUNTEER_SKILLS (VOLUNTEERID),
	FOREIGN KEY (SKILLID) REFERENCES public.SKILLSET (SKILLID)
);

CREATE TABLE CONTACT_TRAN
(
	ID INT PRIMARY KEY,
	PLEDGEID INT, 
	VOLUNTEERID INT,
	DATE_CONTACTED DATE NOT NULL,
	REMARKS VARCHAR(5000),
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (PLEDGEID) REFERENCES public.DONOR_PLEDGE (PLEDGEID),
	FOREIGN KEY (VOLUNTEERID) REFERENCES public.VOLUNTEER_DETAILS (VOLUNTEERID)
);
