
CREATE TABLE VOLUNTEER_DETAILS
(
	VOLUNTEERID INT auto_increment PRIMARY KEY,
	VOLUNTEER_NAME VARCHAR(50) NOT NULL,
	RES_ADDRESS VARCHAR(1000),
	OFF_ADDRESS VARCHAR(1000),
	RES_PHONE VARCHAR(20),
	OFF_PHONE VARCHAR(20),
	MOBILE_PHONE VARCHAR(20),
	EMAIL VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PIN INT,
	STILL_INTERESTED CHAR(1) DEFAULT 'Y',
	BEST_TIME_TO_CONTACT VARCHAR(100),
	TIME_COMMITMENT VARCHAR(100),
	ACTIVE_SINCE DATE DEFAULT GETDATE(),
	LEAVING_DATE DATE,
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50) NOT NULL,
	MODIFIED_DATE DATE NOT NULL
);

INSERT INTO VOLUNTEER_DETAILS
	(VOLUNTEER_NAME
,RES_ADDRESS
,OFF_ADDRESS
,RES_PHONE
,OFF_PHONE
,MOBILE_PHONE
,EMAIL
,CITY
,STATE
,PIN
,STILL_INTERESTED
,BEST_TIME_TO_CONTACT
,TIME_COMMITMENT
,ACTIVE_SINCE
,LEAVING_DATE
,IS_ACTIVE
,MODIFIED_BY
,MODIFIED_DATE)

VALUES
('Santosh I','aaa, bbb street, ccc',NULL,'123 456 2345','222 444 2323','7788372821',
'x@y.com','Mumbai','Maharastra',NULL,NULL,NULL,NULL,NULL,NULL,'Y','santosh',GETDATE()); 

CREATE TABLE DONOR_DETAILS
(
	DONORID INT auto_increment PRIMARY KEY,
	DONOR_NAME VARCHAR(50) NOT NULL,
	RES_ADDRESS VARCHAR(1000),
	OFF_ADDRESS VARCHAR(1000),
	RES_PHONE VARCHAR(20),
	OFF_PHONE VARCHAR(20),
	MOBILE_PHONE VARCHAR(20),
	EMAIL VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PIN INT,
	REFERRAL VARCHAR(50),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	ACTIVE_SINCE DATE DEFAULT GETDATE(),
	MODIFIED_BY VARCHAR(50) NOT NULL,
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (REFERRAL) REFERENCES public.VOLUNTEER_DETAILS (VOLUNTEERID)
);

CREATE TABLE FORM
(
	FORMID INT auto_increment PRIMARY KEY,
	FORM_NAME VARCHAR(50) NOT NULL,
	FORM_DESC VARCHAR(500),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL
);

CREATE TABLE BENEFICIARY
(
	BENEFICIARYID INT auto_increment PRIMARY KEY,
	NGONAME VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(1000),
	PHONE VARCHAR(10),
	EMAIL VARCHAR(10),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PIN INT,
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL
);

CREATE TABLE DONOR_PLEDGE 
(
	PLEDGEID INT auto_increment PRIMARY KEY,
	DONORID INT,
	BENEFICIARYID INT,
	FORMID INT,
	DONATION_FREQUENCY VARCHAR(100) NOT NULL, 
	AMOUNT DOUBLE NOT NULL,
	DATE_FROM DATE,
	DATE_UNTIL DATE,
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (DONORID) REFERENCES public.DONOR_DETAILS (DONORID),
	FOREIGN KEY (FORMID) REFERENCES public.FORM (FORMID),
	FOREIGN KEY (BENEFICIARYID) REFERENCES public.BENEFICIARY (BENEFICIARYID)
);

CREATE TABLE DONATION_DETAILS
(
	TRANSACTION_ID INT auto_increment,
	PLEDGEID INT,
	DEPOSIT_TYPE VARCHAR(25) NOT NULL,
	DEPOSIT_DETAILS VARCHAR(1000),
	DEPOSIT_DATE DATE NOT NULL,
	ENCASHED_DATE DATE NOT NULL,
	AMOUNT DOUBLE NOT NULL,
	VERIFIED char(1) DEFAULT 'N',
	VERIFIED_DATE DATE,
	RECEIPT VARCHAR(1000),
	REMARKS VARCHAR(5000),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (PLEDGEID) REFERENCES DONOR_PLEDGE (PLEDGEID)
);

CREATE TABLE SKILLSET
(
	SKILLID INT auto_increment PRIMARY KEY,
	SKILL_NAME VARCHAR(100) NOT NULL,
	SKILL_DETAILS VARCHAR(1000),
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL
	
);

CREATE TABLE VOLUNTEER_SKILLS
(	
	VOLUNTEERID INT,
	SKILLID INT,
	IS_ACTIVE CHAR(1) DEFAULT 'Y',
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (VOLUNTEERID) REFERENCES public.VOLUNTEER_SKILLS (VOLUNTEERID),
	FOREIGN KEY (SKILLID) REFERENCES public.SKILLSET (SKILLID)
);

CREATE TABLE CONTACT_DETAILS
(
	ID INT auto_increment PRIMARY KEY,
	PLEDGEID INT, 
	VOLUNTEERID INT,
	DATE_CONTACTED DATE NOT NULL,
	REMARKS VARCHAR(5000),
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL,
	FOREIGN KEY (PLEDGEID) REFERENCES public.DONOR_PLEDGE (PLEDGEID),
	FOREIGN KEY (VOLUNTEERID) REFERENCES public.VOLUNTEER_DETAILS (VOLUNTEERID)
);

CREATE TABLE EVENT(
	EVENT_ID INT auto_increment PRIMARY KEY,
	EVENT_NAME VARCHAR(500) NOT NULL,
	EVENT_DESCRIPTION varchar(10000) NOT NULL,
	EVENT_DATE DATE,
	REMARKS VARCHAR(5000),
	MODIFIED_BY VARCHAR(50),
	MODIFIED_DATE DATE NOT NULL
);

CREATE TABLE EVENT_LOG (
	EVENT_ID INT,
	VOLUNTEER_ID INT
	);
	
CREATE TABLE EVENT_LOG_IMAGES(
	EVENT_ID INT,
	IMAGE BINARY NOT NULL
);